version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker
    image: nest-docker-image
    ports:
      - 2812:3000
    volumes:
      - .:/project
      - ./node_modules:/project/node_modules
    networks:
      - nestjs-network

networks:
  nestjs-network:
    driver: bridge
