version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker
    image: nest-docker-image:1.4.3
    ports:
      - 2812:3000
    volumes:
      - ./src:/project/src
      - ./node_modules:/project/node_modules
    networks:
      - nestjs-network

volumes:
  node_modules:
    driver: local

networks:
  nestjs-network:
    driver: bridge
