version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker
    image: nest-docker-image
    ports:
      - 2812:3000
    volumes:
      - ./src:/project/src
      - ./node_modules:/project/node_modules
      - ./package.json:/project/package.json
      - ./package-lock.json:/project/package-lock.json
    networks:
      - nestjs-network

networks:
  nestjs-network:
    driver: bridge
